# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-24 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0004_auto_20160107_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractProviderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_supplier', models.CharField(max_length=200)),
                ('product_name', models.CharField(max_length=200)),
                ('product_quantity', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('attachment', models.FileField(blank=True, max_length=255, null=True, upload_to='images/products/%Y/%m/')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderModel',
            fields=[
                ('abstractprovidermodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='partner.AbstractProviderModel')),
            ],
            bases=('partner.abstractprovidermodel',),
        ),
    ]
