# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-25 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0005_abstractprovidermodel_providermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractprovidermodel',
            name='product_quantity',
            field=models.IntegerField(),
        ),
    ]
